[pytest]
addopts =
    -s
    -v
    --browser chromium
    --browser firefox
    --browser webkit
    --html=report.html
    --self-contained-html

testpaths =
    tests

python_files =
    test_*.py

python_functions =
    test_*